# Generated by Django 5.1.5 on 2025-10-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuestionario', models.CharField(max_length=200, null=True, unique=True)),
                ('descripcion_cuestionario', models.TextField(null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('nombre_usuario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.temas')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('id_cuestionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField()),
                ('id_pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertadas', models.IntegerField()),
                ('falladas', models.IntegerField()),
                ('porcentaje_acierto', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('id_cuestionario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuestionarios.cuestionarios')),
                ('nombre_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.temas')),
            ],
        ),
    ]
