# Generated by Django 5.2.7 on 2025-10-16 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticas',
            name='id_cuestionario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionarios'),
        ),
    ]
