# Generated by Django 5.1.5 on 2025-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='avatar',
            field=models.TextField(blank=True),
        ),
    ]
